name: Publish Release

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
      # Matches tags like v1.0.0, v2.3.5, etc.
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: Install dependencies
        run: make install-deps

      # Build all application variants (macOS & Linux, x86_64 & arm64)
      - name: Build all variants
        run: make build-all

      - name: Create or update GitHub release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "This release was created automatically by GitHub Actions." \
            || echo "Release already exists, proceeding to upload assets..."

      - name: Upload assets to release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # We'll upload all files in ./tmp that start with 'go-aws-sso-'.
          gh release upload ${{ github.ref_name }} ./tmp/aws-sso-login-* --clobber
